# Generated by Django 2.2.7 on 2019-11-13 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 14, 25, 33, 9889), verbose_name='date published'),
        ),
    ]
