# Generated by Django 2.2.7 on 2019-11-13 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191113_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 15, 14, 37, 67966), verbose_name='date published'),
        ),
    ]
