# Generated by Django 2.2.7 on 2019-11-14 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191113_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 10, 35, 22, 949166), verbose_name='date published'),
        ),
    ]
