# Generated by Django 2.2.5 on 2020-02-28 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191114_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 20, 29, 33, 913489), verbose_name='date published'),
        ),
    ]
