# Generated by Django 2.2.5 on 2020-03-03 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200227_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 20, 58, 30, 861554), verbose_name='date published'),
        ),
    ]
